version: "3.8"

services:
  mongodb0:
    image: mongo:7.0
    hostname: mongodb0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "40001"]
    volumes:
      - mongo1_data:/data/db
      - ./init-replica.sh:/docker-entrypoint-initdb.d/init-replica.sh
    ports:
      - "40001:40001"
    restart: unless-stopped

  mongodb1:
    image: mongo:7.0
    hostname: mongodb1
    depends_on:
      - mongodb0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "40002"]
    volumes:
      - mongo2_data:/data/db
    ports:
      - "40002:40002"
    restart: unless-stopped

  mongodb2:
    image: mongo:7.0
    hostname: mongodb2
    depends_on:
      - mongodb1
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "40003"]
    volumes:
      - mongo3_data:/data/db
    ports:
      - "40003:40003"
    restart: unless-stopped
volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
